### ISSUE TITLE
Asset Creation

### ISSUE THREAD

**Issue by YourFavouriteOreo** [greyhavens/bang-game#2]
Just posting this question to ask what software was used in creation of the 3d models? 

I don't know any 3D Modelling Software that uses MXML .

**Comment by samskivert** [comment]
The assets were created in 3D Studio Max and then exported via a custom exporter to the (home grown) mxml format. Unfortunately the original 3DS max source files for the Bang art have been lost to the ravages of time.

**Comment by samskivert** [comment]
FWIW: the 3DS Max export scripts are still in the repo here:

https://github.com/greyhavens/bang-game/tree/master/jme/src/main/ms
